import type { ComponentProps } from "react";
import AlignLeftIcon from "@mui/icons-material/FormatAlignLeft";
import ArrowLeftIcon from "@mui/icons-material/ArrowBack";
import ArrowRightIcon from "@mui/icons-material/ArrowForward";
import ArrowSquareOutIcon from "@mui/icons-material/OpenInNew";
import ArrowUpIcon from "@mui/icons-material/ArrowUpward";
import ArrowsClockwiseIcon from "@mui/icons-material/Refresh";
import BankIcon from "@mui/icons-material/AccountBalance";
import BookmarkSimpleIcon from "@mui/icons-material/BookmarkBorder";
import CalendarIcon from "@mui/icons-material/CalendarMonth";
import CaretDownIcon from "@mui/icons-material/ExpandMore";
import ChevronRightIcon from "@mui/icons-material/ChevronRight";
import CaretUpIcon from "@mui/icons-material/ExpandLess";
import ChartBarIcon from "@mui/icons-material/BarChart";
import ChatCircleIcon from "@mui/icons-material/ChatBubbleOutlined";
import CheckIcon from "@mui/icons-material/Check";
import CheckCircleIcon from "@mui/icons-material/CheckCircleOutlined";
import CircleIcon from "@mui/icons-material/RadioButtonUnchecked";
import CircleNotchIcon from "@mui/icons-material/Loop";
import CopyIcon from "@mui/icons-material/ContentCopy";
import CreditCardIcon from "@mui/icons-material/CreditCard";
import CrownIcon from "@mui/icons-material/WorkspacePremium";
import DotsThreeVerticalIcon from "@mui/icons-material/MoreHoriz";
import DownloadSimpleIcon from "@mui/icons-material/FileDownloadOutlined";
import EyeIcon from "@mui/icons-material/VisibilityOutlined";
import GiftIcon from "@mui/icons-material/Redeem";
import GaugeIcon from "@mui/icons-material/Speed";
import HeartStraightIcon from "@mui/icons-material/FavoriteBorder";
import KeyIcon from "@mui/icons-material/Key";
import LifebuoyIcon from "@mui/icons-material/Support";
import LinkBreakIcon from "@mui/icons-material/LinkOff";
import ListPlusIcon from "@mui/icons-material/PlaylistAdd";
import MagnifyingGlassIcon from "@mui/icons-material/Search";
import MinusIcon from "@mui/icons-material/Remove";
import MusicNotesIcon from "@mui/icons-material/LibraryMusicOutlined";
import MusicNotesPlusIcon from "@mui/icons-material/LibraryAdd";
import MusicNotesSimpleIcon from "@mui/icons-material/MusicNote";
import PackageIcon from "@mui/icons-material/Inventory2Outlined";
import PaperclipIcon from "@mui/icons-material/AttachFile";
import PaperPlaneTiltIcon from "@mui/icons-material/Send";
import PauseIcon from "@mui/icons-material/Pause";
import PencilSimpleIcon from "@mui/icons-material/EditOutlined";
import PlayIcon from "@mui/icons-material/PlayArrow";
import PlayCircleIcon from "@mui/icons-material/PlayCircleOutlined";
import PlusIcon from "@mui/icons-material/Add";
import PlaylistIcon from "@mui/icons-material/QueueMusic";
import ProhibitIcon from "@mui/icons-material/Block";
import QuestionIcon from "@mui/icons-material/HelpOutlined";
import QueueIcon from "@mui/icons-material/QueueMusic";
import ReceiptIcon from "@mui/icons-material/ReceiptLong";
import ShareNetworkIcon from "@mui/icons-material/Share";
import ShieldIcon from "@mui/icons-material/AdminPanelSettingsOutlined";
import SkipBackIcon from "@mui/icons-material/SkipPrevious";
import SkipForwardIcon from "@mui/icons-material/SkipNext";
import SlidersHorizontalIcon from "@mui/icons-material/Tune";
import SparkleIcon from "@mui/icons-material/AutoAwesomeOutlined";
import SpeakerHighIcon from "@mui/icons-material/VolumeUp";
import SpeakerLowIcon from "@mui/icons-material/VolumeDown";
import SpeakerXIcon from "@mui/icons-material/VolumeOff";
import StarIcon from "@mui/icons-material/StarBorder";
import StorefrontIcon from "@mui/icons-material/StorefrontOutlined";
import ThumbsDownIcon from "@mui/icons-material/ThumbDownOutlined";
import TrashIcon from "@mui/icons-material/DeleteOutlined";
import UserIcon from "@mui/icons-material/PersonOutlined";
import UserCircleIcon from "@mui/icons-material/AccountCircleOutlined";
import UsersThreeIcon from "@mui/icons-material/PeopleOutlined";
import WalletIcon from "@mui/icons-material/AccountBalanceWalletOutlined";
import WarningCircleIcon from "@mui/icons-material/ErrorOutlined";
import XIcon from "@mui/icons-material/Close";
import XCircleIcon from "@mui/icons-material/CancelOutlined";
import HeartStraightFilledIcon from "@mui/icons-material/Favorite";
import BookmarkSimpleFilledIcon from "@mui/icons-material/Bookmark";
import StarFilledIcon from "@mui/icons-material/Star";
import MusicNotesFilledIcon from "@mui/icons-material/LibraryMusic";
import UserCircleFilledIcon from "@mui/icons-material/AccountCircle";
import ShieldFilledIcon from "@mui/icons-material/AdminPanelSettings";
import StorefrontFilledIcon from "@mui/icons-material/Storefront";
import SparkleFilledIcon from "@mui/icons-material/AutoAwesome";

/** Point imports keep unused Material icons out of the bundle. Only SvgIcon's
 * runtime is used; the app keeps its own CSS, controls and theme. */
type IconProps = Omit<ComponentProps<typeof AlignLeftIcon>, "color"> & {
  color?: string;
  size?: number | string;
  weight?: "thin" | "light" | "regular" | "bold" | "fill" | "duotone";
};
function icon(Outline: typeof AlignLeftIcon, Filled: typeof AlignLeftIcon = Outline) {
  return function MaterialIcon({ size = 24, weight, fill: _fill, strokeWidth: _stroke, color, fontSize: _fontSize, style, ...props }: IconProps) {
    const Icon = weight === "fill" ? Filled : Outline;
    return <Icon {...props} style={{ width: size, height: size, fontSize: size, flexShrink: 0, color, ...style }} />;
  };
}
export const AlignLeft = icon(AlignLeftIcon);
export const ArrowLeft = icon(ArrowLeftIcon);
export const ArrowRight = icon(ArrowRightIcon);
export const ArrowSquareOut = icon(ArrowSquareOutIcon);
export const ArrowUp = icon(ArrowUpIcon);
export const ArrowsClockwise = icon(ArrowsClockwiseIcon);
export const Bank = icon(BankIcon);
export const BookmarkSimple = icon(BookmarkSimpleIcon, BookmarkSimpleFilledIcon);
export const Calendar = icon(CalendarIcon);
export const CaretDown = icon(CaretDownIcon);
export const CaretRight = icon(ChevronRightIcon);
export const CaretUp = icon(CaretUpIcon);
export const ChartBar = icon(ChartBarIcon);
export const ChatCircle = icon(ChatCircleIcon);
export const Check = icon(CheckIcon);
export const CheckCircle = icon(CheckCircleIcon);
export const Circle = icon(CircleIcon);
export const CircleNotch = icon(CircleNotchIcon);
export const Copy = icon(CopyIcon);
export const CreditCard = icon(CreditCardIcon);
export const Crown = icon(CrownIcon);
export const DotsThreeVertical = icon(DotsThreeVerticalIcon);
export const DownloadSimple = icon(DownloadSimpleIcon);
export const Eye = icon(EyeIcon);
export const Gift = icon(GiftIcon);
export const Gauge = icon(GaugeIcon);
export const HeartStraight = icon(HeartStraightIcon, HeartStraightFilledIcon);
export const Key = icon(KeyIcon);
export const Lifebuoy = icon(LifebuoyIcon);
export const LinkBreak = icon(LinkBreakIcon);
export const ListPlus = icon(ListPlusIcon);
export const MagnifyingGlass = icon(MagnifyingGlassIcon);
export const Minus = icon(MinusIcon);
export const MusicNotes = icon(MusicNotesIcon, MusicNotesFilledIcon);
export const MusicNotesPlus = icon(MusicNotesPlusIcon);
export const MusicNotesSimple = icon(MusicNotesSimpleIcon);
export const Package = icon(PackageIcon);
export const Paperclip = icon(PaperclipIcon);
export const PaperPlaneTilt = icon(PaperPlaneTiltIcon);
export const Pause = icon(PauseIcon);
export const PencilSimple = icon(PencilSimpleIcon);
export const Play = icon(PlayIcon);
export const PlayCircle = icon(PlayCircleIcon);
export const Plus = icon(PlusIcon);
export const Playlist = icon(PlaylistIcon);
export const Prohibit = icon(ProhibitIcon);
export const Question = icon(QuestionIcon);
export const Queue = icon(QueueIcon);
export const Receipt = icon(ReceiptIcon);
export const ShareNetwork = icon(ShareNetworkIcon);
export const Shield = icon(ShieldIcon, ShieldFilledIcon);
export const SkipBack = icon(SkipBackIcon);
export const SkipForward = icon(SkipForwardIcon);
export const SlidersHorizontal = icon(SlidersHorizontalIcon);
export const Sparkle = icon(SparkleIcon, SparkleFilledIcon);
export const SpeakerHigh = icon(SpeakerHighIcon);
export const SpeakerLow = icon(SpeakerLowIcon);
export const SpeakerX = icon(SpeakerXIcon);
export const Star = icon(StarIcon, StarFilledIcon);
export const Storefront = icon(StorefrontIcon, StorefrontFilledIcon);
export const ThumbsDown = icon(ThumbsDownIcon);
export const Trash = icon(TrashIcon);
export const User = icon(UserIcon);
export const UserCircle = icon(UserCircleIcon, UserCircleFilledIcon);
export const UsersThree = icon(UsersThreeIcon);
export const Wallet = icon(WalletIcon);
export const WarningCircle = icon(WarningCircleIcon);
export const X = icon(XIcon);
export const XCircle = icon(XCircleIcon);
export const CaretRightIcon = CaretRight;
export const TextAlignLeft = AlignLeft;
